# Generated by Django 3.2.4 on 2021-06-23 14:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210622_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='template_selector',
            field=wagtail.core.fields.StreamField([('template_choice', wagtail.core.blocks.StructBlock([('template_choice', wagtail.core.blocks.ChoiceBlock(choices=[('classic', 'classic'), ('minimalistic', 'Minimalistic'), ('modern', 'Modern')], label='Design Template'))]))], blank=True, null=True),
        ),
    ]
