# Generated by Django 3.2.4 on 2021-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_template_selector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='template_selector',
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
