# Generated by Django 3.2.4 on 2021-06-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210623_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('minimalistic', 'Minimalistic'), ('modern', 'Modern')], default='classic', max_length=20),
        ),
    ]
