# Generated by Django 3.2.4 on 2021-06-23 18:17

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_template_homepage_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='color_nav',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='homepage',
            name='color_primary',
            field=wagtail_color_panel.fields.ColorField(default='#008037', max_length=7),
        ),
        migrations.AddField(
            model_name='homepage',
            name='color_secondary',
            field=wagtail_color_panel.fields.ColorField(default='#006580', max_length=7),
        ),
        migrations.AddField(
            model_name='homepage',
            name='color_tertiary',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7),
        ),
    ]
