# Generated by Django 3.2.4 on 2021-06-23 18:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0008_auto_20210623_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='color_primary',
            new_name='color1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='color_secondary',
            new_name='color2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='color_tertiary',
            new_name='color3',
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_image',
            field=models.ForeignKey(blank=True, help_text="Add a logo for your site's footer.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=wagtail.core.fields.RichTextField(default='Proudly Made With Wagtail', help_text='Footer text here. Use "DATE_VALUE" to insert current date.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_favicon',
            field=models.ForeignKey(blank=True, help_text='Add a favicon for your site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_logo',
            field=models.ForeignKey(blank=True, help_text='Add a logo for your site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_title',
            field=models.CharField(blank=True, help_text='Enter a title for your site, or leave blank to use a logo instead.', max_length=255),
        ),
    ]
