# Generated by Django 3.2.4 on 2021-06-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210623_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='color_nav',
            new_name='nav_color',
        ),
    ]
