# Generated by Django 3.2.4 on 2021-06-23 18:27

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_color_nav_homepage_nav_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bgcolor',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7),
        ),
    ]
