# Generated by Django 3.2.4 on 2021-06-23 18:34

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='color1',
            field=wagtail_color_panel.fields.ColorField(default='#008037', max_length=7, verbose_name='Color 1'),
        ),
    ]
