# Generated by Django 3.2.4 on 2021-06-23 18:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0012_alter_homepage_color1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='bgcolor',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7, verbose_name='Background Colour'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='color2',
            field=wagtail_color_panel.fields.ColorField(default='#006580', max_length=7, verbose_name='Color 2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='color3',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7, verbose_name='Color 3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_image',
            field=models.ForeignKey(blank=True, help_text="Add a logo for your site's footer.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Footer Logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_text',
            field=wagtail.core.fields.RichTextField(default='Proudly Made With Wagtail', help_text='Footer text here. Use "DATE_VALUE" to insert current date.', verbose_name='Footer Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7, verbose_name='Navbar Color'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_favicon',
            field=models.ForeignKey(blank=True, help_text='Add a favicon for your site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Site Logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_logo',
            field=models.ForeignKey(blank=True, help_text='Add a logo for your site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Site Logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_title',
            field=models.CharField(blank=True, help_text='Enter a title for your site, or leave blank to use a logo instead.', max_length=255, verbose_name='Site Title'),
        ),
    ]
