# Generated by Django 3.2.4 on 2021-06-23 22:05

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210623_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='default_hero_font_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bg_1_font_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Font Colour for Background Color 1 (Optional)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bg_2_font_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Font Colour for Background Color 2 (Optional)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='default_font_color',
            field=wagtail_color_panel.fields.ColorField(default='#000000', max_length=7, null=True, verbose_name='Default Font Colour'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='root_font_size',
            field=models.IntegerField(default=18, null=True, verbose_name='Root Font Size (px)'),
        ),
    ]
