# Generated by Django 3.2.4 on 2021-06-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210623_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='font_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Font-Family Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='font_upload',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Font-Family Link'),
        ),
    ]
