# Generated by Django 3.2.4 on 2021-06-23 23:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210623_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='font_imports',
            field=wagtail.core.fields.StreamField([('font_link', wagtail.core.blocks.StructBlock([('font_link', wagtail.core.blocks.CharBlock(help_text='Link a font, eg. from Google Fonts: <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet" />', required=True))])), ('font_file', wagtail.core.blocks.StructBlock([('font_link', wagtail.core.blocks.CharBlock(help_text='Upload a font file?', required=True))]))], blank=True, null=True),
        ),
    ]
