# Generated by Django 3.2.4 on 2021-06-23 23:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_font_imports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='font_imports',
            field=wagtail.core.fields.StreamField([('font_link', wagtail.core.blocks.StructBlock([('font_link', wagtail.core.blocks.CharBlock(help_text='Link a font, eg. from Google Fonts: <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet" />', required=True))])), ('font_link_fields', wagtail.core.blocks.StructBlock([('font_link_href', wagtail.core.blocks.CharBlock(help_text="Link a font, eg. from Google Fonts: href='https://fonts.googleapis.com/css2?family=Lato'", required=True)), ('font_link_integrity', wagtail.core.blocks.CharBlock(help_text="Font Link Integrity ie: 'sha384-iKbFRxucmOHIcpWdX9NTZ5WETOPm0Goy0WmfyNcl52qSYtc2Buk0NCe6jU1sWWNB'", required=True))])), ('font_file', wagtail.core.blocks.StructBlock([('font_link', wagtail.core.blocks.CharBlock(help_text='Upload a font file?', required=True))]))], blank=True, null=True),
        ),
    ]
