# Generated by Django 3.2.4 on 2021-06-24 00:25

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_font_imports'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='font_weight_heavy',
            field=models.IntegerField(default=800, null=True, verbose_name='Heavy Weight'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='font_weight_medium',
            field=models.IntegerField(default=600, null=True, verbose_name='Medium Weight'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='font_imports',
            field=wagtail.core.fields.StreamField([('font_link', wagtail.core.blocks.StructBlock([('font_link', wagtail.core.blocks.RawHTMLBlock(help_text='Link a font, eg. from Google Fonts:', required=True))])), ('head_link', wagtail.core.blocks.StructBlock([('stylesheet_link', wagtail.core.blocks.RawHTMLBlock(help_text='Link anything, such as bootstrap or javascript files.', required=True))]))], blank=True, null=True),
        ),
    ]
