# Generated by Django 3.2.4 on 2021-06-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210623_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nav_height',
            field=models.IntegerField(default=100, null=True, verbose_name='Navbar Height'),
        ),
    ]
