# Generated by Django 3.2.4 on 2021-06-24 01:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0023_auto_20210623_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nav_logo_max_size',
            field=models.IntegerField(default=200, null=True, verbose_name='Navbar Logo Max Size (px)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nav_text_size',
            field=models.CharField(default='20px', max_length=20, verbose_name='Navbar Font Size (rem or px)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_loader_bgcolor',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#ffffff', max_length=7, null=True, verbose_name='Site Loader Background Colour'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_loader_image',
            field=models.ForeignKey(blank=True, help_text='Add an optional loader gif for your site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Site Loader Gif'),
        ),
    ]
