# Generated by Django 3.2.4 on 2021-06-25 22:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_homepage_social_links_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='social_links_stream',
            field=wagtail.core.fields.StreamField([('social_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(help_text='Destination URL', label='Link URL', required=True)), ('icon', wagtail.core.blocks.CharBlock(help_text='Add the card icon class (eg fab fa-facebook-f).', label='Display Icon', required=True))]))], blank=True, null=True, verbose_name='Social Media Links'),
        ),
    ]
