# Generated by Django 3.2.4 on 2021-06-25 22:38

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_homepage_page_links_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_address',
            field=wagtail.core.fields.RichTextField(default='Ontario, Canada', verbose_name='Footer Address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_company_text',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Additional Company Details'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_company_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Footer Site Title'),
        ),
    ]
