# Generated by Django 3.2.4 on 2021-06-25 22:49

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210625_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='footer_company_title',
            new_name='footer_heading_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='footer_company_text',
            new_name='footer_text_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='footer_address',
            new_name='footer_text_2',
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_heading_2',
            field=models.CharField(blank=True, default='Find Us', max_length=255, verbose_name='Footer Heading Center'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_heading_3',
            field=models.CharField(default='Quick Links', max_length=255, verbose_name='Footer Heading Right'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_text_copyright',
            field=wagtail.core.fields.RichTextField(blank=True, default='DATE_VALUE Proudly Made With Wagtail', help_text='Footer text here. Use "DATE_VALUE" to insert current date.', null=True, verbose_name='Footer Text'),
        ),
    ]
