# Generated by Django 3.2.4 on 2021-06-28 20:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20210625_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='footer_heading_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_heading_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_heading_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_text_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_text_2',
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_design_stream',
            field=wagtail.core.fields.StreamField([('footer_design_classic', wagtail.core.blocks.StructBlock([('footer_heading_1', wagtail.core.blocks.CharBlock(default='', label='Footer Site Title', required=False)), ('footer_text_1', wagtail.core.blocks.RichTextBlock(default='', label='Additional Company Details', required=False)), ('footer_heading_2', wagtail.core.blocks.CharBlock(default='Find Us', label='Footer Heading Center', required=True)), ('footer_text_2', wagtail.core.blocks.RichTextBlock(default='Ontario, Canada', label='Footer Address', required=False)), ('footer_heading_3', wagtail.core.blocks.CharBlock(default='Quick Links', label='Footer Heading Right', required=True))]))], blank=True, null=True, verbose_name='Footer Design'),
        ),
    ]
