# Generated by Django 3.2.4 on 2021-06-29 13:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_homepage_footer_design_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page_links_stream',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='social_links_stream',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='font_imports_stream',
            field=wagtail.core.fields.StreamField([('font_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.RawHTMLBlock(help_text='Link a font, eg. from Google Fonts:', required=True))])), ('head_link', wagtail.core.blocks.StructBlock([('stylesheet_link', wagtail.core.blocks.RawHTMLBlock(help_text='Link anything, such as bootstrap or javascript files.', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_design_stream',
            field=wagtail.core.fields.StreamField([('footer_design_classic', wagtail.core.blocks.StructBlock([('footer_heading_1', wagtail.core.blocks.CharBlock(default='', label='Footer Site Title (Heading Left', required=False)), ('footer_text_1', wagtail.core.blocks.RichTextBlock(default='', label='Additional Company Details', required=False)), ('footer_heading_2', wagtail.core.blocks.CharBlock(default='Find Us', label='Footer Heading Center', required=True)), ('footer_text_2', wagtail.core.blocks.RichTextBlock(default='Ontario, Canada', label='Footer Address', required=False)), ('social_links_stream_container', wagtail.core.blocks.StreamBlock([('social_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(help_text='Destination URL', label='Link URL', required=True)), ('icon', wagtail.core.blocks.CharBlock(help_text='Add the card icon class (eg fab fa-facebook-f).', label='Display Icon', required=True))]))], label='Social Media Links', required=False)), ('page_links_stream_container', wagtail.core.blocks.StreamBlock([('url_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(help_text='Destination URL', label='Link URL', required=True)), ('link_text', wagtail.core.blocks.CharBlock(help_text='', label='Display Text', required=True))]))], label='Page Quick Links', max_num=5, min_num=1, required=True)), ('footer_heading_3', wagtail.core.blocks.CharBlock(default='Quick Links', label='Footer Heading Right', required=True))]))], blank=True, null=True, verbose_name='Footer Design'),
        ),
    ]
