# Generated by Django 3.2.4 on 2021-06-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0049_auto_20210629_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='shrink_navbar_scroll',
            field=models.BooleanField(blank=True, default=True, verbose_name='Shrink Navbar on Scroll?'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_bg_color',
            field=models.CharField(choices=[('1', 'Theme Colour 1'), ('2', 'Theme Colour 2'), ('3', 'Theme Colour 3'), ('default', 'Theme Default Background')], default='default', max_length=20, verbose_name='Footer Background Colour'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_favicon',
            field=models.ForeignKey(blank=True, help_text='Add a favicon for your site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Favicon'),
        ),
    ]
