# Generated by Django 3.2.4 on 2021-06-30 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0051_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allow_subnav',
            field=models.BooleanField(default=False, help_text="NOTE: The sub-menu might not be displayed, even if checked. It depends on how the menu is used in this project's templates.", verbose_name='allow sub-menu for this item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Link to an internal page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Link Text'),
        ),
    ]
