# Generated by Django 3.2.4 on 2021-06-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20210629_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='link_title',
            new_name='link_text',
        ),
    ]
