# Generated by Django 3.2.4 on 2021-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_rename_link_title_menuitem_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='open_in_new_tab',
            field=models.BooleanField(blank=True, default=False, verbose_name='Open in new tab?'),
        ),
    ]
