# Generated by Django 3.2.4 on 2021-07-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_homepage_site_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='bgcolor',
            new_name='bg_color',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='site_loader_bgcolor',
            new_name='site_loader_bg_color',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_logo_max_size',
            field=models.IntegerField(default=200, null=True, verbose_name='Navbar Logo Max Width (px)'),
        ),
    ]
