# Generated by Django 3.2.4 on 2021-07-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20210630_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='nav_color',
            new_name='nav_bg_color',
        ),
    ]
