# Generated by Django 3.2.4 on 2021-07-01 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_rename_nav_color_homepage_nav_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nav_bg_opacity',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Enter a value between 0.0 and 1.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Navbar Background Opacity'),
        ),
    ]
