# Generated by Django 3.2.4 on 2021-07-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20210701_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='nav_text_size',
            new_name='nav_font_size',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_text',
            field=models.CharField(max_length=50, null=True, verbose_name='Link Text'),
        ),
    ]
