# Generated by Django 3.2.4 on 2021-07-02 15:03

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_alter_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bg_3_font_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Font Colour for Background Color 3 (Optional)'),
        ),
    ]
