# Generated by Django 3.2.4 on 2021-07-05 19:15

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_auto_20210705_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='make_button',
            field=models.BooleanField(default=False, verbose_name='Make menu item a button?'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bg_1_font_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', max_length=7, null=True, verbose_name='Font Colour for Background Colour 1 (Optional)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bg_2_font_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', max_length=7, null=True, verbose_name='Font Colour for Background Colour 2 (Optional)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bg_3_font_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', max_length=7, null=True, verbose_name='Font Colour for Background Colour 3 (Optional)'),
        ),
    ]
