# Generated by Django 3.2.4 on 2021-07-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_auto_20210705_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='nav_button_color',
            field=models.CharField(choices=[('1', 'Theme Colour 1'), ('2', 'Theme Colour 2'), ('3', 'Theme Colour 3'), ('default', 'Theme Default Background')], default='2', max_length=20, verbose_name='Button Colour'),
        ),
    ]
