# Generated by Django 3.2.4 on 2021-07-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontimport',
            name='font_import',
            field=models.CharField(help_text='Link a font, eg. from Google Fonts.', max_length=500, null=True, verbose_name='Font Import Link'),
        ),
    ]
