# Generated by Django 3.2.4 on 2021-07-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_alter_fontimport_font_import'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fontimport',
            old_name='font_import',
            new_name='font_import_link',
        ),
    ]
