# Generated by Django 3.2.4 on 2021-07-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_rename_font_import_fontimport_font_import_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontimport',
            name='font_import_link',
            field=models.TextField(help_text='Link a font, eg. from Google Fonts.', max_length=500, null=True, verbose_name='Font Import Link'),
        ),
    ]
