# Generated by Django 3.2.4 on 2021-07-06 16:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_alter_fontimport_font_import_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='font_imports_stream',
        ),
        migrations.AddField(
            model_name='homepage',
            name='html_head_import_stream',
            field=wagtail.core.fields.StreamField([('html_head_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.RawHTMLBlock(help_text='Link a font, eg. from Google Fonts.', required=True))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FontImport',
        ),
    ]
