# Generated by Django 3.2.4 on 2021-07-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_homepage_link_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='link_page',
            new_name='site_logo_link_page',
        ),
    ]
