# Generated by Django 3.2.4 on 2021-07-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_alter_homepage_site_logo_link_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childpage',
            options={'verbose_name': 'Child Page', 'verbose_name_plural': 'Child Pages'},
        ),
    ]
