# Generated by Django 3.2.4 on 2021-07-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_remove_homepage_show_hamburger_active_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_enabled',
            field=models.BooleanField(blank=True, default=True, verbose_name='Enable Site Footer?'),
        ),
    ]
