# Generated by Django 3.2.4 on 2021-07-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_auto_20210726_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='navbar_fixed',
            field=models.BooleanField(blank=True, default=True, verbose_name='Fix Navbar to top of page during scroll?'),
        ),
    ]
