# Generated by Django 3.2.4 on 2021-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0126_alter_homepage_navbar_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='nav_bg_transparent',
            field=models.BooleanField(blank=True, default=False, verbose_name='Navbar Transparent Background?'),
        ),
    ]
